### ISSUE TITLE
crashing_input not working for CVE-2021-3319

### ISSUE THREAD

**Issue by dingiso** [fuzzware-fuzzer/fuzzware-experiments#4]
Hi Scepticz,

The crashing_input is not working for [CVE-2021-3319](https://github.com/fuzzware-fuzzer/fuzzware-experiments/tree/main/03-fuzzing-new-targets/zephyr-os/prebuilt_samples/CVE-2021-3319/POC).

I have tried to use **run.sh** but there is no error in output.
The error should be as other cves below :

```
Execution failed with error code: 6 -> Invalid memory read (UC_ERR_READ_UNMAPPED)
```
And I tried the interactive debug method to set breakpoint using function name and pc number. 

```
>>> Ran out of fuzz

        >>> Read: addr= 0x00000000400e124c size=4 data=0x00006000 (pc 0x0040f8c6)
Exited without crash at 0x0040f8c6 - If no other reason, we ran into one of the limits
```
None of them work
They all failed.

Please have a try 

Thanks,
Dingiso

**Comment by Scepticz** [comment]
Hi Dingiso,

the emulator behavior slightly changed with the latest changes to the emulator. To replay these inputs and have them crash, you need to use the evaluation version of the emulator. This is the following tag: https://github.com/fuzzware-fuzzer/fuzzware/tree/sec22-ae-accepted.

Fuzzing inputs are extremely reliant on exact timings (which is measured by number of basic blocks executed) and interpretation of binary inputs by MMIO models. That means that when due to some changes in the emulator any basic block hook is executed earlier/twice, this is highly likely to change the execution flow for an input.

Best
Tobi

**Comment by Scepticz** [comment]
Alternatively (if the tag gives you trouble with the installation), you can also set the fuzzware-emulator commit to the initial one: https://github.com/fuzzware-fuzzer/fuzzware-emulator/commit/075dbb52f3ba4c20549e81fbee27e8e21086ae56.

Best
Tobi

**Comment by dingiso** [comment]
It works with first commit. 

Thanks,
Tobo
